### ISSUE TITLE
Locality/town names in PAON/SAON are interpreted as the address' locality/town 

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/sorting_office#26]
- First example:
  
  ```
  Winchester Mead
  1 Cold Harbour Close
  Wickham
  Hampshire
  PO17 5PT
  ```
  
  gets parsed into:
  
  ```
  SAON: Mead
  PAON: 1
  Street: Cold Harbour Close
  Locality: Winchester
  Town:
  Postcode: PO17 5PT
  ```
- Second example:
  
  ```
  9 Roding Lodge
  Royston Gardens
  Ilford
  IG1 3ST
  ```
  
  gets parsed into:
  
  ```
  SAON:
  PAON: 9
  Street: Royston Gardens
  Locality: Roding
  Town: Ilford
  Postcode: IG1 3ST 
  ```
  
  Also note that "Roding" _per se_ is not even a locality name, but there are localities that are called "Roding [something]" or "[something] Roding".
